main/postmarketos-ui-phosh: depend on gnome-settings-daemon
Help apk to install the proper gnome-settings-daemon (not the -mobile
variant from gnome-mobile!) when upgrading phosh. I'm assuming this
likely fixes:

ERROR: unable to select packages:
  gnome-settings-daemon-mobile-999948.0-r1:
    breaks: postmarketos-ui-phosh-29-r1[!gnome-settings-daemon-mobile]
    satisfies: phosh-99990.55.0-r2[gnome-settings-daemon] phosh-portalsconf-99990.55.0-r2[gnome-settings-daemon]

Because users reported that they can work around it with:

  apk add !gnome-settings-daemon-mobile gnome-settings-daemon

Related: https://postmarketos.org/edge/2026/06/07/unable-to-select-packages-gnome-settings-daemon-mobile/