main/postmarketos-duranium: remove app store plugin conflicts
These conflicts in the sysext-dev-tools subpkg were intended to prevent
app store plugins from being pulled into the system extension image
(where they would not work as expected and cause confusion.) They were
causing an issue with how packages are snapshot in the duranium build CI
by causing a conflict when it tried to resolve base and sysext package
lists together (so install_if packages were included). The conflict
was from:

error: apk add --simulate failed:
ERROR: unable to select packages:
  gnome-software-plugin-apk2-0.0.3-r1:
    breaks: postmarketos-duranium-sysext-dev-tools-11-r0[!gnome-software-plugin-apk2]
    satisfies: world[gnome-software-plugin-apk]

It's much simpler to just remove these conflicts and add these plugins
to the list of RemovedPackages in duranium's mkosi config so they are
purged before main image is finalized.

Signed-off-by: Clayton Craft <craftyguy@postmarketos.org>